### PR TITLE
fixes and updates on es.json

### PR DESCRIPTION
**Pull request by macorv**
Hi! Made some fixes and updates on the file (see below for details).

_My name is Martin and I am from Argentina. My native language is spanish. My country is under high inflation and find Xumm an useful tool to fight against it, keeping my life savings safe. I think that helping translating the amazing work you have done creating Xumm will spread the app to more people here in Argentina and in LatAm. Hope you find my contribution helpful! Best regards, Martin._

**Summary:**
- Saw that the majority of sentences were written in 3rd person, so I changed some sentences that were in 2nd person to 3rd person.
- Fixed some bad/literal translations. e.g.: line 7 'back' was translated as 'espalda' (that in spanish means a person's back).
- Improved meaning and context of some sentences.
- Line 34: 'exchanges'. Noticed that is used in IOU's screen (Add Asset) to describe the issuers of the Assets. I think it's more familiar for spanish speakers to refer to them as 'emisores' (=issuers) rather than Exchanges. In this particular case, it happen to be both: issuers and exchanges (except Towo Labs). So, my proposal is to call them 'Emisores' in the spanish translation because it's more suitable to describe what those 'entities/parties' do with the assets listed.

### CODE REVIEW

**Comment by WietseWind** [comment]
Thank you! We're going to add translations in V1 of the app, later this year. We really appreciate this!

**Comment by macorv** [comment]
Great! Thank you and the team for the app!

**Comment by WietseWind** [comment]
Hey @macorv! 

We didn't forget about this :) We just imported your entire translation into the XUMM Translation Portal. We're finishing developing the portal as we speak. The portal offer some nice features like:
- [Rewards](https://twitter.com/WietseWind/status/1327034361221435393)
- [Voting before adding a new translation](https://twitter.com/WietseWind/status/1327027020325384192)
- [Live in app preview for context](https://twitter.com/WietseWind/status/1327041810343071748)

The day we launch Translation Portal (about two weeks from now) your contribution will be available for others to vote, complement and of course for you to modify, if you feel like it.

Thank you!! ❤️

**Comment by macorv** [comment]
Thank you Wietse!
Great work on the Translation Portal! When will it go live?

**Comment by WietseWind** [comment]
~ 2 weeks. But if you want early access: drop me a message at hi at wietse.com

**Comment by macorv** [comment]
Thanks, Wietse! Drop a Hi at Twitter (The Translation Portal Thread).

**Comment by WietseWind** [comment]
https://twitter.com/WietseWind/status/1332128319039561728 🚀

**Pull request closed without merging**
