### PR TITLE
Add Dutch translations

### PR DESCRIPTION
**Pull request by martijnjanssen**
I'm a bit unsure what the policy is for some of the terms. I would think it would be good to have a policy for words that are pretty specific for the XRP ledger. Some words don't exist in a specific language, or seem very out-of-place when translating. Some examples:

Source
Destination
Family seed
TrustSet
Escrow
Chain
MessageKey
Node

Maybe have them in quotes? Maybe start each word that is in another language with a capital letter, indicating that it is a name, and not a word?

### CODE REVIEW

**Comment by martijnjanssen** [comment]
If you want, I can also put the changes for the enlish locale in a different PR, so that you can merge that separately.

**Comment by WietseWind** [comment]
I agree. Thanks, and thank you so much for fixing + translating! We will come up with a nice way to translate in a more user friendly way, check changes in the base language and preview (in the live app) your changes in the right context.

**Comment by WietseWind** [comment]
> If you want, I can also put the changes for the enlish locale in a different PR, so that you can merge that separately.

Yes please 😇

**Comment by martijnjanssen** [comment]
> check changes in the base language and preview (in the live app) your changes in the right context.
That would be very nice indeed, to see the translation as a result and in context!

Anyway, I have split the english fixes to #22 and removed them from here, enjoy!

**Comment by WietseWind** [comment]
Thank you very much @martijnjanssen

**Comment by WietseWind** [comment]
Hi @martijnjanssen!

We didn't forget about this :) We just imported your entire translation into the XUMM Translation Portal. We're finishing developing the portal as we speak. The portal offer some nice features like:
- [Rewards](https://twitter.com/WietseWind/status/1327034361221435393)
- [Voting before adding a new translation](https://twitter.com/WietseWind/status/1327027020325384192)
- [Live in app preview for context](https://twitter.com/WietseWind/status/1327041810343071748)

The day we launch Translation Portal (about two weeks from now) your contribution will be available for others to vote, complement and of course for you to modify, if you feel like it.

Thank you!! ❤️

**Comment by WietseWind** [comment]
https://twitter.com/WietseWind/status/1332128319039561728 🚀

**Comment by martijnjanssen** [comment]
I have sent you a message through the chat on the translation portal!

**Pull request closed without merging**
