### PR TITLE
Initial portuguese (Portugal) language translation

### PR DESCRIPTION
**Pull request by VDamas**
Requires review on app to analyse if context and meaning is correct

### CODE REVIEW

**Comment by WietseWind** [comment]
❤️ Thank you @VDamas :D

**Comment by VDamas** [comment]
Thank you for XUMM. 
When released for public i will submit a reviewed version, to adapt text lenghts, and fix some literal translations with better ones.

**Comment by WietseWind** [comment]
Hey @VDamas!

We didn't forget about this :) We just imported your entire translation into the XUMM Translation Portal. We're finishing developing the portal as we speak. The portal offer some nice features like:
- [Rewards](https://twitter.com/WietseWind/status/1327034361221435393)
- [Voting before adding a new translation](https://twitter.com/WietseWind/status/1327027020325384192)
- [Live in app preview for context](https://twitter.com/WietseWind/status/1327041810343071748)

The day we launch Translation Portal (about two weeks from now) your contribution will be available for others to vote, complement and of course for you to modify, if you feel like it.

Thank you!! ❤️

**Comment by WietseWind** [comment]
https://twitter.com/WietseWind/status/1332128319039561728 🚀

**Pull request closed without merging**
