### PR TITLE
Update FR locale

### PR DESCRIPTION
**Pull request by xrpyeur**

### CODE REVIEW

**Comment by WietseWind** [comment]
Awesome @mp3yeur, thank you! I'm waiting for the test to finish and I'll merge :)

**Comment by WietseWind** [comment]
Bonjour @xrpyeur,

We didn't forget about this :) We just imported your entire translation into the XUMM Translation Portal. We're finishing developing the portal as we speak. The portal offer some nice features like:
- [Rewards](https://twitter.com/WietseWind/status/1327034361221435393)
- [Voting before adding a new translation](https://twitter.com/WietseWind/status/1327027020325384192)
- [Live in app preview for context](https://twitter.com/WietseWind/status/1327041810343071748)

The day we launch Translation Portal (about two weeks from now) your contribution will be available for others to vote, complement and of course for you to modify, if you feel like it.

Thank you!! ❤️

**Comment by xrpyeur** [comment]
Thanks a lot for your work Wietse! It's a pleasure to help an excellent project like Xumm and XRPL.

PS : i try to learn programming at school "ecole 42", i would like to help xrpl dev soon as possible.

Best regards!

**Comment by WietseWind** [comment]
https://twitter.com/WietseWind/status/1332128319039561728 🚀

**Pull request closed without merging**
