### PR TITLE
German Translation

### PR DESCRIPTION
**Pull request by florianweirauch**
When Apple finally approves the App, I'll test the app and check, how my translation fits.
It should be fine already but, I just want to make sure.
Have a nice day!

### CODE REVIEW

**Comment by WietseWind** [comment]
Awesome!! Thank you @floshej <3

**Comment by WietseWind** [comment]
Hi @florianweirauch,

We didn't forget about this :) We just imported your entire translation into the XUMM Translation Portal. We're finishing developing the portal as we speak. The portal offer some nice features like:
- [Rewards](https://twitter.com/WietseWind/status/1327034361221435393)
- [Voting before adding a new translation](https://twitter.com/WietseWind/status/1327027020325384192)
- [Live in app preview for context](https://twitter.com/WietseWind/status/1327041810343071748)

The day we launch Translation Portal (about two weeks from now) your contribution will be available for others to vote, complement and of course for you to modify, if you feel like it.

Thank you!! ❤️

**Comment by florianweirauch** [comment]
That's awesome Wietse!
Thank you for letting us help!
I will check once more if all translations are correct in the app.

**Comment by WietseWind** [comment]
The portal is unfinished but you can already correct, check context and add translations, see https://translate.xumm.dev (please don't share the URL yet).

After logging in, first select your languages in Profile, then go to "To translate" in the menu to make changes / suggestions / add translations :)

Please note I'm live editing in that portal as it's still in dev, so you may experience the occasional error: they will be fixed fast though, as I'm making daily progress.

**Comment by WietseWind** [comment]
https://twitter.com/WietseWind/status/1332128319039561728 🚀

**Pull request closed without merging**
