### PR TITLE
Ar.js

### PR DESCRIPTION
**Pull request by CryptoPrince9**
Kindly note that Arabic alignment is right to left. and that I need to see the translation on the interface for a final check (or at least screenshots) to fix any errors.

### CODE REVIEW

**Comment by WietseWind** [comment]
Thank you 🍻  I really appreciate it. Thanks for the RTL heads up (I was aware, but it will need special attention indeed).

We have some ideas to make translating + context a bit easier, we'll work on that after the beta, so in the mean time I think from update to update there will some testing and updating here and

**Comment by CryptoPrince9** [comment]
Thanks. It would help if the translation has the following:
1-A real time visual of how the translated part looks like in the app. 
2- If translation files contains the words only not the code and they use distributed translation. And the code can pull translated parts without anyone missing with the code itself 
--
--
Kind regards 
Ahmed Khalil, M. Ed., EMBA, M.Sc. Digital Currencies (P.), PCC, MGSCC Certified Executive and Team Coach, CMA Certified Professional Transformative Coach, Global Leadership Assessment (GLA360) Certified Professional, CIDwICT
Executive Coach | Founder |Co-founder | Blockchain Advisor | Board Member| Board Chairman
Heaven's Gate OÜ
Europe Middle East Africa Consultancy OÜ
International Coach Masters OÜ
Marshall Goldsmith Stakeholders Centered Coaching
Phone: +966532805198
Whatsapp: +201005131010
Email: aakwaqf@gmail.com, Akhalil@internationalcoachmasters.com, Ahmedkhalil@emea-consultancy.eu, Ahmedkhalil@heavens-gate.net
Websites: 
www.internationalcoachmasters.com
www.emea-consultancy.eu
www.heavens-gate.net
LinkedIn: www.linkedin.com/in/aakwaqf
https://sccoaching.com/coach/akhalil1
For coaching appointments: https://clarity.fm/ahmedkhalil
Or
https://contact.experty.io/aakwaqf
XRP Transactions: rfYHL7ESRwvcGGGf79wFCRqYaZisd3BZvv
VET Transactions:
0x160AeB6BeE740413Af63ea6B8b385B994553f742
Ethereum Transactions:
0x6746dA3a61f96532820b3A2424deed86c5C565B9
Bitcoin Transactions:
3FfZkcogW3fDTJ8si6LmiCVmXKv91DtGok
PayPal Payments:
https://www.paypal.me/aakwaqf
Xumm payments:
rpAx21eFgJA6n8UWZfPjmkvaFzHzuvS8t6
----
Sent from Huawei Mate 20 Pro Monday, 06 April 2020, 02:24AM +03:00 from Wietse Wind  notifications@github.com :

**Comment by WietseWind** [comment]
Hey @CryptoPrince9,

We didn't forget about this :) We just imported your entire translation into the XUMM Translation Portal. We're finishing developing the portal as we speak. The portal offer some nice features like:
- [Rewards](https://twitter.com/WietseWind/status/1327034361221435393)
- [Voting before adding a new translation](https://twitter.com/WietseWind/status/1327027020325384192)
- [Live in app preview for context](https://twitter.com/WietseWind/status/1327041810343071748)

The day we launch Translation Portal (about two weeks from now) your contribution will be available for others to vote, complement and of course for you to modify, if you feel like it.

Thank you!! ❤️

**Comment by WietseWind** [comment]
https://twitter.com/WietseWind/status/1332128319039561728 🚀

**Pull request closed without merging**
